-- Schema for Real Estate CMS
SET NAMES utf8mb4;
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(120) NOT NULL,
	email VARCHAR(190) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	role ENUM('super','editor') NOT NULL DEFAULT 'editor',
	created_at DATETIME NULL,
	updated_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS permissions (
	id INT AUTO_INCREMENT PRIMARY KEY,
	role ENUM('super','editor') NOT NULL,
	permission VARCHAR(100) NOT NULL,
	UNIQUE KEY role_permission (role, permission)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
	id INT AUTO_INCREMENT PRIMARY KEY,
	`key` VARCHAR(100) NOT NULL UNIQUE,
	`value` TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sliders (
	id INT AUTO_INCREMENT PRIMARY KEY,
	image VARCHAR(255) NOT NULL,
	headline VARCHAR(255) NULL,
	subtext VARCHAR(255) NULL,
	cta_text VARCHAR(120) NULL,
	cta_url VARCHAR(255) NULL,
	sort_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS features (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(120) NOT NULL,
	body VARCHAR(255) NOT NULL,
	sort_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pages (
	id INT AUTO_INCREMENT PRIMARY KEY,
	slug VARCHAR(120) NOT NULL UNIQUE,
	title VARCHAR(190) NOT NULL,
	body MEDIUMTEXT NULL,
	meta_title VARCHAR(190) NULL,
	meta_description VARCHAR(255) NULL,
	updated_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS partners (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(190) NOT NULL,
	logo VARCHAR(255) NULL,
	sort_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS projects (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(190) NOT NULL,
	slug VARCHAR(190) NOT NULL UNIQUE,
	status ENUM('completed','ongoing','upcoming') NOT NULL,
	city VARCHAR(120) NULL,
	address VARCHAR(255) NULL,
	cover_image VARCHAR(255) NULL,
	handover_date DATE NULL,
	area_sqft INT NULL,
	floors INT NULL,
	units_total INT NULL,
	overview MEDIUMTEXT NULL,
	amenities MEDIUMTEXT NULL,
	map_iframe MEDIUMTEXT NULL,
	created_at DATETIME NULL,
	updated_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS project_gallery (
	id INT AUTO_INCREMENT PRIMARY KEY,
	project_id INT NOT NULL,
	path VARCHAR(255) NOT NULL,
	alt VARCHAR(190) NULL,
	sort_order INT NOT NULL DEFAULT 0,
	FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS units (
	id INT AUTO_INCREMENT PRIMARY KEY,
	project_id INT NOT NULL,
	type VARCHAR(120) NOT NULL,
	bedrooms INT NULL,
	size_sqft INT NULL,
	price DECIMAL(12,2) NULL,
	status ENUM('available','booked','sold') NOT NULL DEFAULT 'available',
	FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS team (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(120) NOT NULL,
	role VARCHAR(120) NOT NULL,
	photo VARCHAR(255) NULL,
	bio VARCHAR(255) NULL,
	twitter VARCHAR(255) NULL,
	linkedin VARCHAR(255) NULL,
	sort_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS testimonials (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(120) NOT NULL,
	photo VARCHAR(255) NULL,
	quote VARCHAR(255) NOT NULL,
	created_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS categories (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(190) NOT NULL,
	slug VARCHAR(190) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tags (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(190) NOT NULL,
	slug VARCHAR(190) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS posts (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(190) NOT NULL,
	slug VARCHAR(190) NOT NULL UNIQUE,
	cover_image VARCHAR(255) NULL,
	excerpt VARCHAR(255) NULL,
	body MEDIUMTEXT NULL,
	status ENUM('draft','published') NOT NULL DEFAULT 'draft',
	published_at DATETIME NULL,
	created_at DATETIME NULL,
	updated_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS post_categories (
	post_id INT NOT NULL,
	category_id INT NOT NULL,
	PRIMARY KEY (post_id, category_id),
	FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
	FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS post_tags (
	post_id INT NOT NULL,
	tag_id INT NOT NULL,
	PRIMARY KEY (post_id, tag_id),
	FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
	FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS csr_posts (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(190) NOT NULL,
	slug VARCHAR(190) NOT NULL UNIQUE,
	cover_image VARCHAR(255) NULL,
	excerpt VARCHAR(255) NULL,
	body MEDIUMTEXT NULL,
	created_at DATETIME NULL,
	updated_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS jobs (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(190) NOT NULL,
	slug VARCHAR(190) NOT NULL UNIQUE,
	dept VARCHAR(120) NULL,
	type VARCHAR(120) NULL,
	location VARCHAR(120) NULL,
	excerpt VARCHAR(255) NULL,
	description MEDIUMTEXT NULL,
	requirements MEDIUMTEXT NULL,
	created_at DATETIME NULL,
	updated_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS applications (
	id INT AUTO_INCREMENT PRIMARY KEY,
	job_id INT NOT NULL,
	name VARCHAR(120) NOT NULL,
	email VARCHAR(190) NOT NULL,
	phone VARCHAR(120) NULL,
	cv_path VARCHAR(255) NULL,
	reviewed TINYINT(1) NOT NULL DEFAULT 0,
	created_at DATETIME NULL,
	FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS enquiries (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(120) NOT NULL,
	email VARCHAR(190) NOT NULL,
	topic VARCHAR(50) NOT NULL,
	message TEXT NOT NULL,
	resolved TINYINT(1) NOT NULL DEFAULT 0,
	created_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS media (
	id INT AUTO_INCREMENT PRIMARY KEY,
	filename VARCHAR(255) NOT NULL,
	path VARCHAR(255) NOT NULL,
	mime VARCHAR(120) NULL,
	size INT NULL,
	created_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS menus (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(120) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS menu_items (
	id INT AUTO_INCREMENT PRIMARY KEY,
	menu_id INT NOT NULL,
	title VARCHAR(190) NOT NULL,
	url VARCHAR(255) NOT NULL,
	parent_id INT NULL,
	sort_order INT NOT NULL DEFAULT 0,
	FOREIGN KEY (menu_id) REFERENCES menus(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS activity_log (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NULL,
	action VARCHAR(190) NOT NULL,
	payload TEXT NULL,
	created_at DATETIME NULL,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;