<?php
return [
	'sliders' => [
		'table' => 'sliders',
		'title' => 'Sliders',
		'order_by' => 'sort_order ASC',
		'fields' => [
			'image' => ['label' => 'Image', 'type' => 'image', 'upload_dir' => 'slides', 'required' => true, 'list' => true],
			'headline' => ['label' => 'Headline', 'type' => 'text', 'required' => false, 'list' => true],
			'subtext' => ['label' => 'Subtext', 'type' => 'text', 'required' => false],
			'cta_text' => ['label' => 'CTA Text', 'type' => 'text'],
			'cta_url' => ['label' => 'CTA URL', 'type' => 'text'],
			'sort_order' => ['label' => 'Order', 'type' => 'number'],
		],
	],
	'features' => [
		'table' => 'features',
		'title' => 'Features',
		'order_by' => 'sort_order ASC',
		'fields' => [
			'title' => ['label' => 'Title', 'type' => 'text', 'required' => true, 'list' => true],
			'body' => ['label' => 'Body', 'type' => 'text'],
			'sort_order' => ['label' => 'Order', 'type' => 'number'],
		],
	],
	'partners' => [
		'table' => 'partners',
		'title' => 'Partners',
		'order_by' => 'sort_order ASC',
		'fields' => [
			'name' => ['label' => 'Name', 'type' => 'text', 'list' => true],
			'logo' => ['label' => 'Logo', 'type' => 'image', 'upload_dir' => 'brands', 'list' => true],
			'sort_order' => ['label' => 'Order', 'type' => 'number'],
		],
	],
	'pages' => [
		'table' => 'pages',
		'title' => 'Pages',
		'fields' => [
			'slug' => ['label' => 'Slug', 'type' => 'text', 'list' => true],
			'title' => ['label' => 'Title', 'type' => 'text', 'list' => true],
			'body' => ['label' => 'Body', 'type' => 'wysiwyg'],
			'meta_title' => ['label' => 'Meta Title', 'type' => 'text'],
			'meta_description' => ['label' => 'Meta Description', 'type' => 'text'],
		],
	],
	'projects' => [
		'table' => 'projects',
		'title' => 'Projects',
		'fields' => [
			'title' => ['label' => 'Title', 'type' => 'text', 'list' => true],
			'slug' => ['label' => 'Slug', 'type' => 'text', 'list' => true],
			'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['completed' => 'Completed','ongoing' => 'Ongoing','upcoming' => 'Upcoming'], 'list' => true],
			'city' => ['label' => 'City', 'type' => 'text', 'list' => true],
			'address' => ['label' => 'Address', 'type' => 'text'],
			'cover_image' => ['label' => 'Cover Image', 'type' => 'image', 'upload_dir' => 'projects', 'list' => true],
			'handover_date' => ['label' => 'Handover Date', 'type' => 'date'],
			'area_sqft' => ['label' => 'Area (sqft)', 'type' => 'number'],
			'floors' => ['label' => 'Floors', 'type' => 'number'],
			'units_total' => ['label' => 'Units Total', 'type' => 'number'],
			'overview' => ['label' => 'Overview', 'type' => 'wysiwyg'],
			'amenities' => ['label' => 'Amenities', 'type' => 'textarea'],
			'map_iframe' => ['label' => 'Map Iframe', 'type' => 'textarea'],
		],
	],
	'project_gallery' => [
		'table' => 'project_gallery',
		'title' => 'Project Gallery',
		'fields' => [
			'project_id' => ['label' => 'Project', 'type' => 'select_query', 'query' => 'SELECT id, title FROM projects ORDER BY title'],
			'path' => ['label' => 'Image', 'type' => 'image', 'upload_dir' => 'gallery'],
			'alt' => ['label' => 'Alt Text', 'type' => 'text'],
			'sort_order' => ['label' => 'Order', 'type' => 'number'],
		],
	],
	'units' => [
		'table' => 'units',
		'title' => 'Units',
		'fields' => [
			'project_id' => ['label' => 'Project', 'type' => 'select_query', 'query' => 'SELECT id, title FROM projects ORDER BY title'],
			'type' => ['label' => 'Type', 'type' => 'text', 'list' => true],
			'bedrooms' => ['label' => 'Bedrooms', 'type' => 'number', 'list' => true],
			'size_sqft' => ['label' => 'Size (sqft)', 'type' => 'number', 'list' => true],
			'price' => ['label' => 'Price', 'type' => 'number', 'list' => true],
			'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['available' => 'Available','booked' => 'Booked','sold' => 'Sold'], 'list' => true],
		],
	],
	'team' => [
		'table' => 'team',
		'title' => 'Team',
		'fields' => [
			'name' => ['label' => 'Name', 'type' => 'text', 'list' => true],
			'role' => ['label' => 'Role', 'type' => 'text', 'list' => true],
			'photo' => ['label' => 'Photo', 'type' => 'image', 'upload_dir' => 'team', 'list' => true],
			'bio' => ['label' => 'Short Bio', 'type' => 'textarea'],
			'linkedin' => ['label' => 'LinkedIn', 'type' => 'text'],
			'twitter' => ['label' => 'Twitter', 'type' => 'text'],
			'sort_order' => ['label' => 'Order', 'type' => 'number'],
		],
	],
	'testimonials' => [
		'table' => 'testimonials',
		'title' => 'Testimonials',
		'fields' => [
			'name' => ['label' => 'Name', 'type' => 'text', 'list' => true],
			'photo' => ['label' => 'Photo', 'type' => 'image', 'upload_dir' => 'testimonials'],
			'quote' => ['label' => 'Quote', 'type' => 'textarea', 'list' => true],
		],
	],
	'categories' => [
		'table' => 'categories',
		'title' => 'Categories',
		'fields' => [
			'title' => ['label' => 'Title', 'type' => 'text', 'list' => true],
			'slug' => ['label' => 'Slug', 'type' => 'text', 'list' => true],
		],
	],
	'tags' => [
		'table' => 'tags',
		'title' => 'Tags',
		'fields' => [
			'title' => ['label' => 'Title', 'type' => 'text', 'list' => true],
			'slug' => ['label' => 'Slug', 'type' => 'text', 'list' => true],
		],
	],
	'posts' => [
		'table' => 'posts',
		'title' => 'Blog Posts',
		'fields' => [
			'title' => ['label' => 'Title', 'type' => 'text', 'list' => true],
			'slug' => ['label' => 'Slug', 'type' => 'text', 'list' => true],
			'cover_image' => ['label' => 'Cover Image', 'type' => 'image', 'upload_dir' => 'posts'],
			'excerpt' => ['label' => 'Excerpt', 'type' => 'text'],
			'body' => ['label' => 'Body', 'type' => 'wysiwyg'],
			'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['draft' => 'Draft','published' => 'Published']],
			'published_at' => ['label' => 'Publish Date', 'type' => 'datetime'],
			'categories' => ['label' => 'Categories', 'type' => 'manyToMany', 'pivot' => ['table' => 'post_categories','this' => 'post_id','other' => 'category_id'], 'options_query' => 'SELECT id, title FROM categories'],
			'tags' => ['label' => 'Tags', 'type' => 'manyToMany', 'pivot' => ['table' => 'post_tags','this' => 'post_id','other' => 'tag_id'], 'options_query' => 'SELECT id, title FROM tags'],
		],
	],
	'csr_posts' => [
		'table' => 'csr_posts',
		'title' => 'CSR Posts',
		'fields' => [
			'title' => ['label' => 'Title', 'type' => 'text', 'list' => true],
			'slug' => ['label' => 'Slug', 'type' => 'text', 'list' => true],
			'cover_image' => ['label' => 'Cover Image', 'type' => 'image', 'upload_dir' => 'csr'],
			'excerpt' => ['label' => 'Excerpt', 'type' => 'text'],
			'body' => ['label' => 'Body', 'type' => 'wysiwyg'],
		],
	],
	'jobs' => [
		'table' => 'jobs',
		'title' => 'Jobs',
		'fields' => [
			'title' => ['label' => 'Title', 'type' => 'text', 'list' => true],
			'slug' => ['label' => 'Slug', 'type' => 'text', 'list' => true],
			'dept' => ['label' => 'Department', 'type' => 'text', 'list' => true],
			'type' => ['label' => 'Type', 'type' => 'text'],
			'location' => ['label' => 'Location', 'type' => 'text'],
			'excerpt' => ['label' => 'Excerpt', 'type' => 'text'],
			'description' => ['label' => 'Description', 'type' => 'wysiwyg'],
			'requirements' => ['label' => 'Requirements', 'type' => 'wysiwyg'],
		],
	],
	'applications' => [
		'table' => 'applications',
		'title' => 'Applications',
		'read_only' => true,
		'fields' => [
			'job_id' => ['label' => 'Job', 'type' => 'select_query', 'query' => 'SELECT id, title FROM jobs'],
			'name' => ['label' => 'Name', 'type' => 'text', 'list' => true],
			'email' => ['label' => 'Email', 'type' => 'text', 'list' => true],
			'phone' => ['label' => 'Phone', 'type' => 'text'],
			'cv_path' => ['label' => 'CV', 'type' => 'file_link', 'base' => '/uploads/'],
			'reviewed' => ['label' => 'Reviewed', 'type' => 'select', 'options' => ['0' => 'No', '1' => 'Yes'], 'list' => true],
			'created_at' => ['label' => 'Submitted', 'type' => 'datetime', 'list' => true],
		],
	],
	'enquiries' => [
		'table' => 'enquiries',
		'title' => 'Enquiries',
		'read_only' => true,
		'fields' => [
			'name' => ['label' => 'Name', 'type' => 'text', 'list' => true],
			'email' => ['label' => 'Email', 'type' => 'text', 'list' => true],
			'topic' => ['label' => 'Topic', 'type' => 'text', 'list' => true],
			'message' => ['label' => 'Message', 'type' => 'textarea'],
			'resolved' => ['label' => 'Resolved', 'type' => 'select', 'options' => ['0' => 'No','1' => 'Yes'], 'list' => true],
			'created_at' => ['label' => 'Date', 'type' => 'datetime', 'list' => true],
		],
	],
	'users' => [
		'table' => 'users',
		'title' => 'Users',
		'fields' => [
			'name' => ['label' => 'Name', 'type' => 'text', 'list' => true],
			'email' => ['label' => 'Email', 'type' => 'text', 'list' => true],
			'password' => ['label' => 'Password', 'type' => 'password'],
			'role' => ['label' => 'Role', 'type' => 'select', 'options' => ['super' => 'Super Admin','editor' => 'Editor'], 'list' => true],
		],
	],
	'media' => [
		'table' => 'media',
		'title' => 'Media Library',
		'fields' => [
			'filename' => ['label' => 'File', 'type' => 'file', 'upload_dir' => 'media'],
			'mime' => ['label' => 'MIME', 'type' => 'text', 'list' => true],
			'size' => ['label' => 'Size', 'type' => 'number', 'list' => true],
		],
	],
	'menus' => [
		'table' => 'menus',
		'title' => 'Menus',
		'fields' => [
			'name' => ['label' => 'Name', 'type' => 'text', 'list' => true],
		],
	],
	'menu_items' => [
		'table' => 'menu_items',
		'title' => 'Menu Items',
		'fields' => [
			'menu_id' => ['label' => 'Menu', 'type' => 'select_query', 'query' => 'SELECT id, name FROM menus'],
			'title' => ['label' => 'Title', 'type' => 'text', 'list' => true],
			'url' => ['label' => 'URL', 'type' => 'text', 'list' => true],
			'parent_id' => ['label' => 'Parent', 'type' => 'select_query', 'query' => 'SELECT id, title FROM menu_items'],
			'sort_order' => ['label' => 'Order', 'type' => 'number', 'list' => true],
		],
	],
];